import '@/styles/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from '@/components/Navbar';
const inter = Inter({ subsets: ['latin'] });
import { ThemeProvider } from '@/context/ThemeContext';

export const metadata: Metadata = {
  title: 'Next 13 + TypeScript',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeProvider>
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
      </ThemeProvider>
    </html>
  );
}
